POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Indicado 3",
  "email": "indicado3@email.com",
  "referrer": "d2570791-62ea-4f0c-a381-fd9c6524376c"
}

###

GET http://localhost:3333/invites/e0616e64-430a-46b9-aa42-f64e3687def5

###

GET http://localhost:3333/subscribers/e0616e64-430a-46b9-aa42-f64e3687def5/ranking/clicks

###

GET http://localhost:3333/subscribers/e0616e64-430a-46b9-aa42-f64e3687def5/ranking/count

###

GET http://localhost:3333/subscribers/e0616e64-430a-46b9-aa42-f64e3687def5/ranking/position

###

GET http://localhost:3333/ranking

###
